---
- name: install python-apt on ansible < 1.6.0 and ubuntu et al
  sudo: yes
  raw: >
    if command -v apt-get; then
       python -c "import apt" ||
       (command -v apt-get && apt-get install -y python-apt);
    fi

- name: install python-pycurl on ansible < 1.6.0 and ubuntu et al
  sudo: yes
  raw: >
    if command -v apt-get; then
       python -c "import pycurl" ||
       (command -v apt-get && apt-get install -y python-pycurl);
    fi

- name: apt-get update
  apt: update_cache=true cache_valid_time=3600
  sudo: yes

- name: install gnucash
  apt: name=gnucash
  sudo: yes
